/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Advance = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Opt(IDL.Text),
  'labourId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'amount' : IDL.Float64,
  'contractId' : IDL.Nat,
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'multiplier' : IDL.Float64,
  'isSettled' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'machineExp' : IDL.Float64,
  'contractAmount' : IDL.Float64,
});
export const Labour = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const MeshColumn = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'contractId' : IDL.Nat,
});
export const ColumnType = IDL.Variant({
  'Bed' : IDL.Null,
  'Mesh' : IDL.Nat,
  'Paper' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : IDL.Nat,
  'columnType' : ColumnType,
  'value' : IDL.Float64,
  'labourId' : IDL.Nat,
  'contractId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContractDetails = IDL.Record({
  'contract' : Contract,
  'meshColumns' : IDL.Vec(MeshColumn),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdvanceEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createContract' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createLabour' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createMeshColumn' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'deleteLabour' : IDL.Func([IDL.Nat], [], []),
  'getAdvancesForContract' : IDL.Func([IDL.Nat], [IDL.Vec(Advance)], ['query']),
  'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getAllLabours' : IDL.Func([], [IDL.Vec(Labour)], ['query']),
  'getAllMeshColumns' : IDL.Func([], [IDL.Vec(MeshColumn)], ['query']),
  'getAttendanceForContract' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfileInternal' : IDL.Func(
      [],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContractById' : IDL.Func([IDL.Nat], [IDL.Opt(Contract)], ['query']),
  'getContractDetails' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContractDetails)],
      ['query'],
    ),
  'getContractsBySettlement' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Contract)],
      ['query'],
    ),
  'getMeshColumnsForContract' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MeshColumn)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markContractAsSettled' : IDL.Func([IDL.Nat], [], []),
  'resetAdmin' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAttendanceEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, ColumnType, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'unsettleContract' : IDL.Func([IDL.Nat], [], []),
  'updateContract' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateLabour' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Advance = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Opt(IDL.Text),
    'labourId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'amount' : IDL.Float64,
    'contractId' : IDL.Nat,
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'multiplier' : IDL.Float64,
    'isSettled' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'machineExp' : IDL.Float64,
    'contractAmount' : IDL.Float64,
  });
  const Labour = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const MeshColumn = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'contractId' : IDL.Nat,
  });
  const ColumnType = IDL.Variant({
    'Bed' : IDL.Null,
    'Mesh' : IDL.Nat,
    'Paper' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Nat,
    'columnType' : ColumnType,
    'value' : IDL.Float64,
    'labourId' : IDL.Nat,
    'contractId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContractDetails = IDL.Record({
    'contract' : Contract,
    'meshColumns' : IDL.Vec(MeshColumn),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdvanceEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createContract' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createLabour' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createMeshColumn' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'deleteLabour' : IDL.Func([IDL.Nat], [], []),
    'getAdvancesForContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Advance)],
        ['query'],
      ),
    'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getAllLabours' : IDL.Func([], [IDL.Vec(Labour)], ['query']),
    'getAllMeshColumns' : IDL.Func([], [IDL.Vec(MeshColumn)], ['query']),
    'getAttendanceForContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfileInternal' : IDL.Func(
        [],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContractById' : IDL.Func([IDL.Nat], [IDL.Opt(Contract)], ['query']),
    'getContractDetails' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContractDetails)],
        ['query'],
      ),
    'getContractsBySettlement' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Contract)],
        ['query'],
      ),
    'getMeshColumnsForContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MeshColumn)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markContractAsSettled' : IDL.Func([IDL.Nat], [], []),
    'resetAdmin' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAttendanceEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, ColumnType, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'unsettleContract' : IDL.Func([IDL.Nat], [], []),
    'updateContract' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateLabour' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };