/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Advance {
  'id' : bigint,
  'note' : [] | [string],
  'labourId' : bigint,
  'createdAt' : bigint,
  'amount' : number,
  'contractId' : bigint,
}
export interface Attendance {
  'id' : bigint,
  'columnType' : ColumnType,
  'value' : number,
  'labourId' : bigint,
  'contractId' : bigint,
}
export type ColumnType = { 'Bed' : null } |
  { 'Mesh' : bigint } |
  { 'Paper' : null };
export interface Contract {
  'id' : bigint,
  'multiplier' : number,
  'isSettled' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'machineExp' : number,
  'contractAmount' : number,
}
export interface ContractDetails {
  'contract' : Contract,
  'meshColumns' : Array<MeshColumn>,
}
export interface Labour {
  'id' : bigint,
  'name' : string,
  'notes' : [] | [string],
  'phone' : [] | [string],
}
export interface MeshColumn {
  'id' : bigint,
  'name' : string,
  'contractId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdvanceEntry' : ActorMethod<
    [bigint, bigint, number, [] | [string]],
    bigint
  >,
  'createContract' : ActorMethod<[string, number, number, number], bigint>,
  'createLabour' : ActorMethod<[string, [] | [string], [] | [string]], bigint>,
  'createMeshColumn' : ActorMethod<[bigint, string], bigint>,
  'deleteLabour' : ActorMethod<[bigint], undefined>,
  'getAdvancesForContract' : ActorMethod<[bigint], Array<Advance>>,
  'getAllContracts' : ActorMethod<[], Array<Contract>>,
  'getAllLabours' : ActorMethod<[], Array<Labour>>,
  'getAllMeshColumns' : ActorMethod<[], Array<MeshColumn>>,
  'getAttendanceForContract' : ActorMethod<[bigint], Array<Attendance>>,
  'getCallerUserProfileInternal' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContractById' : ActorMethod<[bigint], [] | [Contract]>,
  'getContractDetails' : ActorMethod<[bigint], [] | [ContractDetails]>,
  'getContractsBySettlement' : ActorMethod<[boolean], Array<Contract>>,
  'getMeshColumnsForContract' : ActorMethod<[bigint], Array<MeshColumn>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markContractAsSettled' : ActorMethod<[bigint], undefined>,
  'resetAdmin' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAttendanceEntry' : ActorMethod<
    [bigint, bigint, ColumnType, number],
    bigint
  >,
  'unsettleContract' : ActorMethod<[bigint], undefined>,
  'updateContract' : ActorMethod<
    [bigint, string, number, number, number],
    undefined
  >,
  'updateLabour' : ActorMethod<
    [bigint, string, [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];