/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Labour {
    id: bigint;
    name: string;
    notes?: string;
    phone?: string;
}
export interface Attendance {
    id: bigint;
    columnType: ColumnType;
    value: number;
    labourId: bigint;
    contractId: bigint;
}
export interface ContractDetails {
    contract: Contract;
    meshColumns: Array<MeshColumn>;
}
export interface MeshColumn {
    id: bigint;
    name: string;
    contractId: bigint;
}
export type ColumnType = {
    __kind__: "Bed";
    Bed: null;
} | {
    __kind__: "Mesh";
    Mesh: bigint;
} | {
    __kind__: "Paper";
    Paper: null;
};
export interface Contract {
    id: bigint;
    multiplier: number;
    isSettled: boolean;
    name: string;
    createdAt: bigint;
    machineExp: number;
    contractAmount: number;
}
export interface Advance {
    id: bigint;
    note?: string;
    labourId: bigint;
    createdAt: bigint;
    amount: number;
    contractId: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAdvanceEntry(contractId: bigint, labourId: bigint, amount: number, note: string | null): Promise<bigint>;
    createContract(name: string, multiplier: number, contractAmount: number, machineExp: number): Promise<bigint>;
    createLabour(name: string, phone: string | null, notes: string | null): Promise<bigint>;
    createMeshColumn(contractId: bigint, name: string): Promise<bigint>;
    deleteLabour(labourId: bigint): Promise<void>;
    getAdvancesForContract(contractId: bigint): Promise<Array<Advance>>;
    getAllContracts(): Promise<Array<Contract>>;
    getAllLabours(): Promise<Array<Labour>>;
    getAllMeshColumns(): Promise<Array<MeshColumn>>;
    getAttendanceForContract(contractId: bigint): Promise<Array<Attendance>>;
    getCallerUserProfileInternal(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContractById(contractId: bigint): Promise<Contract | null>;
    getContractDetails(contractId: bigint): Promise<ContractDetails | null>;
    getContractsBySettlement(isSettled: boolean): Promise<Array<Contract>>;
    getMeshColumnsForContract(contractId: bigint): Promise<Array<MeshColumn>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markContractAsSettled(contractId: bigint): Promise<void>;
    resetAdmin(userSecret: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAttendanceEntry(contractId: bigint, labourId: bigint, columnType: ColumnType, value: number): Promise<bigint>;
    unsettleContract(contractId: bigint): Promise<void>;
    updateContract(id: bigint, name: string, multiplier: number, contractAmount: number, machineExp: number): Promise<void>;
    updateLabour(id: bigint, name: string, phone: string | null, notes: string | null): Promise<void>;
}
import type { Advance as _Advance, Attendance as _Attendance, ColumnType as _ColumnType, Contract as _Contract, ContractDetails as _ContractDetails, Labour as _Labour, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAdvanceEntry(arg0: bigint, arg1: bigint, arg2: number, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdvanceEntry(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdvanceEntry(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createContract(arg0: string, arg1: number, arg2: number, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createLabour(arg0: string, arg1: string | null, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLabour(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLabour(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createMeshColumn(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMeshColumn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMeshColumn(arg0, arg1);
            return result;
        }
    }
    async deleteLabour(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLabour(arg0);
            return result;
        }
    }
    async getAdvancesForContract(arg0: bigint): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancesForContract(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancesForContract(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContracts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContracts();
            return result;
        }
    }
    async getAllLabours(): Promise<Array<Labour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLabours();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLabours();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMeshColumns(): Promise<Array<MeshColumn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMeshColumns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMeshColumns();
            return result;
        }
    }
    async getAttendanceForContract(arg0: bigint): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceForContract(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceForContract(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfileInternal(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfileInternal();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfileInternal();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractById(arg0: bigint): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractDetails(arg0: bigint): Promise<ContractDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractDetails(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractDetails(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractsBySettlement(arg0: boolean): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractsBySettlement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractsBySettlement(arg0);
            return result;
        }
    }
    async getMeshColumnsForContract(arg0: bigint): Promise<Array<MeshColumn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeshColumnsForContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeshColumnsForContract(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markContractAsSettled(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markContractAsSettled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContractAsSettled(arg0);
            return result;
        }
    }
    async resetAdmin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdmin(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAttendanceEntry(arg0: bigint, arg1: bigint, arg2: ColumnType, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.setAttendanceEntry(arg0, arg1, to_candid_ColumnType_n21(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAttendanceEntry(arg0, arg1, to_candid_ColumnType_n21(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async unsettleContract(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsettleContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsettleContract(arg0);
            return result;
        }
    }
    async updateContract(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateLabour(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabour(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabour(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_Advance_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Advance): Advance {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Attendance_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ColumnType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColumnType): ColumnType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Labour_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Labour): Labour {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contract]): Contract | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContractDetails]): ContractDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    notes: [] | [string];
    phone: [] | [string];
}): {
    id: bigint;
    name: string;
    notes?: string;
    phone?: string;
} {
    return {
        id: value.id,
        name: value.name,
        notes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.notes)),
        phone: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    columnType: _ColumnType;
    value: number;
    labourId: bigint;
    contractId: bigint;
}): {
    id: bigint;
    columnType: ColumnType;
    value: number;
    labourId: bigint;
    contractId: bigint;
} {
    return {
        id: value.id,
        columnType: from_candid_ColumnType_n14(_uploadFile, _downloadFile, value.columnType),
        value: value.value,
        labourId: value.labourId,
        contractId: value.contractId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    note: [] | [string];
    labourId: bigint;
    createdAt: bigint;
    amount: number;
    contractId: bigint;
}): {
    id: bigint;
    note?: string;
    labourId: bigint;
    createdAt: bigint;
    amount: number;
    contractId: bigint;
} {
    return {
        id: value.id,
        note: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.note)),
        labourId: value.labourId,
        createdAt: value.createdAt,
        amount: value.amount,
        contractId: value.contractId
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bed: null;
} | {
    Mesh: bigint;
} | {
    Paper: null;
}): {
    __kind__: "Bed";
    Bed: null;
} | {
    __kind__: "Mesh";
    Mesh: bigint;
} | {
    __kind__: "Paper";
    Paper: null;
} {
    return "Bed" in value ? {
        __kind__: "Bed",
        Bed: value.Bed
    } : "Mesh" in value ? {
        __kind__: "Mesh",
        Mesh: value.Mesh
    } : "Paper" in value ? {
        __kind__: "Paper",
        Paper: value.Paper
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Advance>): Array<Advance> {
    return value.map((x)=>from_candid_Advance_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Labour>): Array<Labour> {
    return value.map((x)=>from_candid_Labour_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ColumnType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColumnType): _ColumnType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Bed";
    Bed: null;
} | {
    __kind__: "Mesh";
    Mesh: bigint;
} | {
    __kind__: "Paper";
    Paper: null;
}): {
    Bed: null;
} | {
    Mesh: bigint;
} | {
    Paper: null;
} {
    return value.__kind__ === "Bed" ? {
        Bed: value.Bed
    } : value.__kind__ === "Mesh" ? {
        Mesh: value.Mesh
    } : value.__kind__ === "Paper" ? {
        Paper: value.Paper
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
